RSS3-Network/Global-Indexer

internal/database/client.go
internal/database/dialer/cockroachdb/client_bridge.go
internal/database/dialer/cockroachdb/migration/20240130105138_add_timestamp_index_for_bridge_transactions.sql
internal/database/dialer/cockroachdb/table/bridge_transaction.go
internal/hub/handler_bridge.go
internal/service/indexer/l1/indexer_bridge.go
schema/bridge_event.go
schema/bridge_transaction.go

feat: add indexes for bridge transactions table

---

internal/database/client.go
internal/database/dialer/cockroachdb/client_bridge.go
internal/database/dialer/cockroachdb/client_stake.go
internal/database/dialer/cockroachdb/migration/20240201120853_add_timestamp_index_for_stake_transactions.sql
internal/database/dialer/cockroachdb/table/stake_transaction.go
internal/hub/handler_bridge.go
internal/hub/handler_stake.go
internal/service/indexer/l2/indexer_stake.go
schema/bridge_transaction.go
schema/stake_chip.go
schema/stake_event.go
schema/stake_transaction.go

feat: add indexes for stake transactions table

---

internal/service/indexer/l1/indexer.go
internal/service/indexer/l2/indexer.go

fix(indexer): invalid retry logic

---

internal/database/dialer/cockroachdb/client_stake.go
internal/hub/handler_stake.go
internal/hub/model/stake_staker.go
internal/hub/server.go
schema/stake_chip.go

http://localhost/stake/wallets
<details>
```json
{
"data": [
{
"user": "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1",
"chips": [
{
"node": "0x827431510a5d249ce4fdb7f00c83a3353f471848",
"ids": [
54,
24,
25,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50,
52,
53,
55,
56,
57,
58,
59,
60,
61,
62,
63,
51
]
},
{
"node": "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1",
"ids": [
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
22,
3,
4
]
},
{
"node": "0x6727a51caefcaf1bc189a8316ea09f844644b195",
"ids": [
23,
500,
499,
498,
497,
496
]
},
{
"node": "0x08d66b34054a174841e2361bd4746ff9f4905cc2",
"ids": [
474,
473,
345,
472,
471,
470,
469,
468,
275,
276,
277,
278,
279,
280,
281,
282,
283,
284,
285,
286,
287,
288,
289,
290,
291,
292,
293,
294, …
```

feat(hub): staker list api

---

contract/l1/contract.go
contract/l2/contract.go

docs: https://www.notion.so/rss3/VSL-Docs-de15bd9e92d6413d8fa4e0f1ccb0ba9e#4644d77921184db9b86d88240454b3c6

chore(contract): update l1 and l2 contract address

---

cmd/main.go
docs/openapi.yaml
internal/database/client.go
internal/database/dialer/cockroachdb/client_node.go
internal/database/dialer/cockroachdb/migration/20240308083713_add_hide_tax_rate_field_for_nodes.sql
internal/database/dialer/cockroachdb/table/node.go
internal/hub/data_node.go
internal/hub/handler_node.go
internal/hub/model/node.go
internal/hub/server.go
internal/service/indexer/l2/indexer.go
internal/service/indexer/l2/indexer_stake.go
internal/service/indexer/server.go
schema/node.go

```diff
{
"data": [
{
"id": 3,
"address": "0x3b6d02a24df681ffdf621d35d70aba7adaac07c1",
"name": "Albert",
"description": "Albert's alpha node",
"taxRateBasisPoints": 2000,
"isPublicGood": false,
"operationPoolTokens": "10200000000000000000000",
"stakingPoolTokens": "65000000000000000000000",
"totalShares": "65000000000000000000000",
"slashedTokens": "0",
"status": "registered",
"lastHeartbeat": 0,
"local": null,
"avatar": {
"name": "Node Avatar",
"description": "",
"image": "http://localhost/nodes/0x3B6D02A24Df681FFdf621D35D70ABa7adaAc07c1/avatar.svg"
},
"minTokensToStake": "0",
"createdAt": 1709814672
},
{
"id": 2,
"address": "0x77bd134fcbe9b7591b109b99bc15b2420fd4ed7d",
"name": "BUG",
"description": "polebug is here",
"taxRateBasisPoints": 1000,
"isPublicGood": false, …
```

feat: support for hidden node tax rate

---

deploy/config.yaml
internal/config/config.go
internal/service/indexer/l2/config.go
internal/service/indexer/l2/indexer.go
internal/service/indexer/server.go

Provides the same batch indexing implementation for the L2 indexer as for the L1 indexer.

feat(indexer): batch indexing for l2 indexer

---

internal/service/indexer/l2/indexer_stake.go

The current APY calculation did not consider tax deducted.

fix: APY calculation

---

internal/service/hub/handler/nta/network.go
internal/service/hub/model/nta/network.go
internal/service/hub/server.go

```bash
/nta/networks/{network}/workers
/nta/networks
```

feat: add /networks endpoint

---

docs/openapi.yaml
internal/database/dialer/cockroachdb/client_epoch.go
internal/database/dialer/cockroachdb/table/epoch.go
internal/database/dialer/cockroachdb/table/epoch_item.go
internal/service/hub/handler/nta/epoch.go
internal/service/hub/model/nta/epoch.go
internal/service/indexer/l2/indexer_stake.go
internal/service/settler/operation_rewards.go
internal/service/settler/settler.go
internal/service/settler/utils.go
schema/epoch.go
schema/epoch_trigger.go

https://github.com/RSS3-Network/Explorer/pull/24 must be merged before shipping this to production.

docs: add openapi docs for epochs

---

internal/database/dialer/cockroachdb/migration/20240425092038_add_node_type_field_for_node_info_table.sql
internal/database/dialer/cockroachdb/table/node.go
internal/service/hub/handler/nta/node_info.go
internal/service/hub/handler/nta/node_register.go
internal/service/hub/handler/nta/nta.go
internal/service/hub/hub.go
internal/service/hub/model/nta/node_register.go
schema/node.go

Resolved https://github.com/RSS3-Network/Global-Indexer/issues/141.

feat: support heartbeat callback and add node types

---

internal/service/hub/handler/dsl/activity.go
internal/service/hub/handler/nta/epoch.go
internal/service/hub/handler/nta/network.go
internal/service/hub/handler/nta/node_challenge.go
internal/service/hub/handler/nta/node_event.go
internal/service/hub/handler/nta/node_hide_tax_rate.go
internal/service/hub/handler/nta/node_info.go
internal/service/hub/handler/nta/node_register.go
internal/service/hub/handler/nta/operation.go
internal/service/hub/handler/nta/snapshot.go
internal/service/hub/handler/nta/stake_chip.go
internal/service/hub/handler/nta/stake_staking.go
internal/service/hub/handler/nta/stake_transaction.go
internal/service/hub/model/errorx/error.go
internal/service/hub/model/errorx/error_code.go

- Add a `Details` field for ErrorResponse.
- Avoid exposing InternalError details.

refactor: errorx

---

internal/service/hub/handler/nta/network.go
internal/service/hub/server.go

Pending https://github.com/RSS3-Network/Node/pull/291

feat: support /nta/networks/get_endpoint_config

---

internal/service/indexer/l2/indexer_stake.go

When a wallet stakes some tokens to a **Public Good Node**, the `nodeAddr` field in the `Staked` event will be the genesis address.

fix(indexer): unsupported public good node staked event

---

internal/service/hub/handler/dsl/activity.go
internal/service/hub/handler/dsl/enforcer/score_maintainer.go

1. Initialize and synchronize members in the sorted set during setup
2. Adjust several error outputs in GetAccountActivities

fix: sorted set members 

---

internal/service/settler/server.go

related to https://github.com/RSS3-Network/Global-Indexer/pull/287

fix(settler): use finalized block

---

contract/l1/contract.go
contract/l2/contract.go
internal/client/ethereum/chain.go
internal/config/flag/flag.go
internal/database/client.go
internal/database/dialer/cockroachdb/client_bridge.go
internal/database/dialer/cockroachdb/client_node.go
internal/database/dialer/cockroachdb/client_stake.go
internal/database/dialer/cockroachdb/migration/20240719095143_create_chain_id_and_block_number_index_for_bridge_and_stake_tables.sql
internal/service/indexer/internal/handler/l1/handler.go
internal/service/indexer/internal/handler/l2/handler.go

The PR resolved the legacy of #287.

fix(indexer): auto confirms previously finalized blocks

---

common/httputil/http.go
internal/service/hub/handler/dsl/router/router.go

1. Exclude node demotions caused by 'context deadline exceeded' errors due to manual cancellations.
2. Specific sets of errors should not be retried.

fix: exclude manually cancel error

---

internal/database/dialer/cockroachdb/client_stake.go
internal/service/hub/handler/nta/stake_staking.go
internal/service/scheduler/snapshot/operator_profit/operator_profit.go
internal/service/scheduler/snapshot/staker_profit/staker_profit.go
schema/staker_profit_snapshot.go

Changed the calculation method for chips from real-time to snapshot-based due to current real-time computation limitations.

feat(hub): update the calculation logic of staker profit

---

internal/database/dialer/cockroachdb/client_stake.go

feat(hub): exclude claimed tokens for staker api

---

deploy/config.example.yaml
internal/config/config.go

Add parameters to the configuration file for the distributor to control the maximum number of demotions.

feat: add distributor config

---

common/httputil/http.go

set the HTTP timeout to 30 seconds.

chore: set http default timeout 

---

internal/service/scheduler/enforcer/epoch_fresher/epoch_fresher.go

add a retry mechanism to handle occasional errors.

fix: add retry in epoch fresher

---

docs/openapi.json
internal/database/dialer/cockroachdb/table/stake_transaction.go
internal/service/hub/handler/nta/stake_staking.go
internal/service/hub/handler/nta/stake_transaction.go
internal/service/hub/model/nta/stake_transaction.go
internal/service/indexer/internal/handler/l2/handler_staking_v1.go
internal/service/indexer/internal/handler/l2/handler_staking_v2.go
schema/stake_transaction.go

Related: https://github.com/RSS3-Network/Global-Indexer/issues/374

feat(hub): return only chip_ids for staking transactions

---

contract/l1/contract.go
contract/l2/contract.go
deploy/config.example.yaml
docs/openapi.json
internal/config/config.go
internal/service/hub/handler/nta/nta.go
internal/service/hub/handler/nta/token.go
internal/service/hub/hub.go
internal/service/hub/server.go

add two nta apis:
1. `/nta/token/supply`
2. `/nta/token/tvl`

feat: add total supply and tvl api

---

contract/l2/abi/NetworkParams.abi
contract/l2/contract.go
contract/l2/contract_network_params.go
docs/openapi.json
internal/service/hub/handler/nta/network.go
internal/service/hub/model/nta/network.go
internal/service/hub/server.go

deprecated apis
```
1. /nta/networks
2. /nta/networks/:network_name/list_workers
3. /nta/networks/:network_name/workers/:worker_name
4. /nta/networks/endpoint_config
```
added api
```
1. /nta/networks/config
```

chore: add network config api

---

docs/openapi.json
internal/service/hub/model/dsl/decentralized.go
internal/service/hub/model/nta/bridge_transaction.go
internal/service/hub/model/nta/epoch.go
internal/service/hub/model/nta/node_info.go
internal/service/hub/model/nta/stake_chip.go
internal/service/hub/model/nta/stake_staking.go
internal/service/hub/model/nta/stake_transaction.go

Update default limit to 50 to reduce pagination.

chore: update default limit to 50, max to 100

---

internal/service/hub/handler/dsl/enforcer/handle_status.go
internal/service/hub/handler/dsl/enforcer/maintain_epoch_data.go
internal/service/hub/handler/dsl/enforcer/maintain_epoch_data_test.go
internal/service/hub/handler/dsl/enforcer/node_request.go
internal/service/hub/handler/nta/node_register.go

related https://github.com/RSS3-Network/Node/pull/624

feat: change Node api path
